import { db } from './prisma';
import { CHAINS } from './validation';
import { getEvmTokens, getEvmTokenTransfers, getSolanaTokens } from './tokens';
import { sendMail } from './mail';
const PRICE_IDS={ETH:'ethereum',SOL:'solana',BTC:'bitcoin',POL:'polygon-ecosystem-token',BNB:'binancecoin',AVAX:'avalanche-2',xDAI:'xdai',MNT:'mantle',CELO:'celo',CRO:'crypto-com-chain',GLMR:'moonbeam',MOVR:'moonriver',METIS:'metis-token',BERA:'berachain-bera',S:'sonic-3',SEI:'sei-token'};
async function rpc(rpc,method,params){const r=await fetch(rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),cache:'no-store'});if(!r.ok)throw Error(`RPC ${r.status}`);const j=await r.json();if(j.error)throw Error(j.error.message||'RPC error');return j.result;}
async function readBalance(wallet){const c=CHAINS[wallet.chain];if(c.kind==='evm'){const hex=await rpc(c.rpc,'eth_getBalance',[wallet.address,'latest']);return Number(BigInt(hex))/1e18;}if(c.kind==='solana'){const r=await rpc('https://api.mainnet-beta.solana.com','getBalance',[wallet.address]);return (r?.value||0)/1e9;}if(c.kind==='bitcoin'){const r=await fetch(`https://blockstream.info/api/address/${encodeURIComponent(wallet.address)}`,{cache:'no-store'});if(!r.ok)throw Error(`Bitcoin API ${r.status}`);const j=await r.json();return ((j.chain_stats?.funded_txo_sum||0)-(j.chain_stats?.spent_txo_sum||0))/1e8;}throw Error('Unsupported chain');}
async function prices(symbols){const ids=[...new Set(symbols.map(s=>PRICE_IDS[s]).filter(Boolean))];if(!ids.length)return{};try{const r=await fetch(`https://api.coingecko.com/api/v3/simple/price?ids=${ids.join(',')}&vs_currencies=usd`,{next:{revalidate:30}});const j=await r.json();return Object.fromEntries(Object.entries(PRICE_IDS).map(([s,id])=>[s,j[id]?.usd||0]));}catch{return{};}}
async function sendAlert(user,w,amount,usd,kind='deposit',txHash=''){if(!user.emailVerifiedAt)return false;const min=Number(user.minimumNotificationUsd||0);if(usd<min)return false;if(kind==='withdrawal'&&!user.notifyWithdrawals)return false;if(kind==='deposit'&&!user.notifyDeposits)return false;await db.notification.create({data:{userId:user.id,walletId:w.id,chain:w.chain,symbol:CHAINS[w.chain].symbol,amount:String(amount),usdValue:String(usd),txHash:txHash||null,type:kind}});await sendMail({to:user.email,subject:`${kind==='withdrawal'?'📤 Withdrawal':'💰 Deposit'} — ${w.label}`,text:`${amount.toFixed(8)} ${CHAINS[w.chain].symbol} ${kind==='withdrawal'?'left':'arrived'} in ${w.label}.

Network: ${CHAINS[w.chain].name}
Wallet: ${w.address}
Estimated value: $${usd.toFixed(2)}${txHash?`
Transaction: ${txHash}`:''}

Crypto Vault is watch-only; no private key is stored.`});return true;}
export async function monitorUser(userId){const user=await db.user.findUnique({where:{id:userId},include:{wallets:true}});if(!user)return{checked:0,alerts:0};const ps=await prices(user.wallets.map(w=>CHAINS[w.chain]?.symbol));let alerts=0;for(const w of user.wallets){const c=CHAINS[w.chain];if(!c)continue;try{const amount=await readBalance(w);const previous=Number(w.lastNativeAmount||'0');const increase=amount-previous;const decrease=previous-amount;const usdValue=amount*(ps[c.symbol]||0);await db.wallet.update({where:{id:w.id},data:{lastNativeAmount:String(amount),lastNativeUsdValue:String(usdValue),lastCheckedAt:new Date()}});if(w.lastCheckedAt&&increase>0){if(await sendAlert(user,w,increase,increase*(ps[c.symbol]||0),'deposit'))alerts++;}else if(w.lastCheckedAt&&decrease>0&&user.notifyWithdrawals){if(await sendAlert(user,w,decrease,decrease*(ps[c.symbol]||0),'withdrawal'))alerts++;}
      if(user.emailVerifiedAt&&user.tokenMonitoringEnabled&&c.kind==='evm'&&user.notifyTokenDeposits){const transfers=await getEvmTokenTransfers(w);const since=w.lastCheckedAt?new Date(w.lastCheckedAt).getTime():Date.now();for(const t of transfers){if((t.to||'').toLowerCase()===w.address.toLowerCase()&&new Date(t.timestamp).getTime()>since){const min=Number(user.minimumNotificationUsd||0);if(t.usdValue>=min){await db.notification.create({data:{userId:user.id,walletId:w.id,chain:w.chain,symbol:t.symbol,amount:String(t.amount),usdValue:String(t.usdValue),txHash:t.txHash,type:'token-deposit'}});await sendMail({to:user.email,subject:`🪙 ${t.symbol} received — ${w.label}`,text:`${t.amount} ${t.symbol} arrived in ${w.label}.

Network: ${c.name}
Estimated value: $${t.usdValue.toFixed(2)}
Transaction: ${t.txHash||'N/A'}

Crypto Vault is watch-only.`});alerts++;}}}}
    }catch(e){console.error(`[monitor] ${w.chain}/${w.address}:`,e.message)}}return{checked:user.wallets.length,alerts};}
export async function monitorAll(){const users=await db.user.findMany({select:{id:true}});let checked=0,alerts=0;for(const u of users){const r=await monitorUser(u.id);checked+=r.checked;alerts+=r.alerts;}return{users:users.length,checked,alerts};}
export async function getPortfolio(userId){const user=await db.user.findUnique({where:{id:userId},include:{wallets:true}});if(!user)return null;const ps=await prices(user.wallets.map(w=>CHAINS[w.chain]?.symbol));const wallets=[];const tokens=[];for(const w of user.wallets){const c=CHAINS[w.chain];const native=Number(w.lastNativeAmount||0);const nativeUsd=native*(ps[c.symbol]||0);wallets.push({...w,nativeUsdValue:nativeUsd});if(user.tokenMonitoringEnabled){if(c.kind==='evm')tokens.push(...(await getEvmTokens(w)).map(t=>({...t,walletId:w.id,walletLabel:w.label,chainName:c.name})));else if(c.kind==='solana')tokens.push(...(await getSolanaTokens(w.address)).map(t=>({...t,walletId:w.id,walletLabel:w.label,chainName:c.name})));}}
return {wallets,tokens,totalUsd:wallets.reduce((s,w)=>s+w.nativeUsdValue,0)+tokens.reduce((s,t)=>s+t.usdValue,0),tokenMonitoringEnabled:user.tokenMonitoringEnabled};}
